version: '3'

volumes:
  local_mysql_data: {}


networks:
  blood_bank_network:
    name: blood_bank_network
    driver: bridge
    ipam:
      driver: default

services:
  app:
    container_name: django-blood
    build:
      context: .
      dockerfile: Django-Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      blood_bank_network:
        aliases:
          - app
  
  db:
    container_name: mysql-blood
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'blood_bank_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - local_mysql_data:/var/lib/mysql
    ports:
      - "3316:3306"
    networks:
      blood_bank_network:
        aliases:
          - db
  

  react:
    container_name: react-blood
    build:
      context: .
      dockerfile: React-Dockerfile
    volumes:
      - './front:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    networks:
      blood_bank_network:
        aliases:
          - react