# Generated by Django 3.1.7 on 2022-04-08 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodBank', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfusion_date', models.DateField(verbose_name='Expiry Date')),
                ('volume', models.IntegerField(verbose_name='Volume')),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodBank.bloodbank', verbose_name='Blood Bank')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital', verbose_name='Hospital')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.recipients', verbose_name='Recipients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
