# Generated by Django 3.1.7 on 2022-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender')),
                ('blood_group', models.CharField(choices=[('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative'), ('AB+', 'AB positive'), ('AB-', 'AB negative'), ('O+', 'O positive'), ('O-', 'O negative')], default='A+', max_length=3, verbose_name='Blood Group')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('email', models.CharField(max_length=80, verbose_name='email')),
                ('diseases', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Diseases')),
            ],
        ),
    ]
