# Generated by Django 3.1.7 on 2022-04-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative'), ('AB+', 'AB positive'), ('AB-', 'AB negative'), ('O+', 'O positive'), ('O-', 'O negative')], default='A+', max_length=3, verbose_name='Blood Group')),
                ('collection_date', models.DateField(verbose_name='Collection Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('total_volume', models.IntegerField(verbose_name='Total Volume')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donors', verbose_name='Donor')),
            ],
        ),
    ]
